import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const dinAlternate = localFont({
  src: [
    {
      path: "../assets/fonts/DINAlternate-Bold.woff",
    },
  ],
  display: "swap",
  variable: "--font-din-alternate",
});

const tungsten = localFont({
  src: [
    {
      path: "../assets/fonts/Tungsten.woff",
    },
    {
      path: "../assets/fonts/Tungsten.woff2",
    },
    {
      path: "../assets/fonts/Tungsten.eot",
    },
  ],
  display: "swap",
  variable: "--font-tungsten",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${dinAlternate.className} ${tungsten.className}`}
    >
      <body>{children}</body>
    </html>
  );
}
