import { Metadata } from "next";
import MainPageLayout from "@/components/layout";

export const metadata: Metadata = {
  title: "Home | GunZ Website",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <MainPageLayout>
      <div className=""></div>
    </MainPageLayout>
  );
}
